include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    # We keep explicit Key? key for compatibility; silence the hint.
    use_super_parameters: false
